# Generated by Django 4.1.2 on 2022-10-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dailycheck", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="signature",
            constraint=models.UniqueConstraint(
                fields=("school", "bus", "check_date", "direction"),
                name="unique_signature_with_school_bus_date_and_direction",
            ),
        ),
    ]
