# Generated by Django 4.1.2 on 2022-10-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dailycheck", "0004_alter_signature_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="signature",
            options={"ordering": ["-check_date"]},
        ),
        migrations.RemoveConstraint(
            model_name="attendance",
            name="unique_student_with_school_date_and_direction",
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("school", "check_date", "direction", "student"),
                name="unique_student_with_school_date_direction_and_student",
            ),
        ),
        migrations.AddConstraint(
            model_name="signature",
            constraint=models.UniqueConstraint(
                fields=("school", "bus", "check_date", "direction"),
                name="unique_signature_with_school_bus_date_and_direction",
            ),
        ),
    ]
