# Generated by Django 4.1.2 on 2022-10-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dailycheck", "0005_alter_signature_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="direction",
            field=models.CharField(
                choices=[("coming", "Coming"), ("leaving", "Leaving")], max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="signature",
            name="direction",
            field=models.CharField(
                choices=[("coming", "Coming"), ("leaving", "Leaving")], max_length=7
            ),
        ),
    ]
