# Generated by Django 4.1.2 on 2022-10-18 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dailycheck", "0006_alter_attendance_direction_alter_signature_direction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="signature",
            old_name="absent_total",
            new_name="absent_count",
        ),
        migrations.RenameField(
            model_name="signature",
            old_name="bus_total",
            new_name="actual_count",
        ),
    ]
